import { board } from '../dtfDescription/dtfDescription.js';
declare function JSONSaver(FileName: string, json2Parse: any, extension: string): void;
declare function emptyBoard(esn: string, time: number): board;
declare function arraysMatch(arr1: any[], arr2: any[]): boolean;
declare function dtfParse(path: string): board;
declare function findObjectFromPath(path: string, key: string, value: any): board | undefined;
declare function findFromESN(esn: string, Time?: number): board;
declare function findLatestOfModule(Board: board, ModNumber: number): board;
declare function findLatestOfCell(Board: board, ModNumber: number, Cell: number): board;
declare function findLatestOfPin(Board: board, ModNumber: number, Cell: number, Pin: number): board;
export { JSONSaver, emptyBoard, arraysMatch, dtfParse, findFromESN, findLatestOfModule, findObjectFromPath, findLatestOfCell, findLatestOfPin };
